### ISSUE TITLE
ROS packages for object_detection and semantic_segmentation

### ISSUE THREAD

**Issue by wetoo-cando** [introlab/t-top#105]
Great project!

While there is object_detection and semantic_segmentation training code in https://github.com/introlab/t-top/tree/main/tools/dnn_training, these two functionalities are missing in https://github.com/introlab/t-top/tree/main/ros/perceptions.

Can you share your plans on this?

**Comment by mamaheux** [comment]
Thanks!

The ROS node performing the object detection and semantic segmentation is [video_analyzer](https://github.com/introlab/t-top/tree/main/ros/perceptions/video_analyzer).

For clarification, the training code the object_detection is not great. So, I used the yolov7 code to train a model, then I used the code in dnn_training to convert the model to TensorRT.
